// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaLgAi_upwqDHysBRUgGHTNaovJUQIY0M',
    appId: '1:428503827243:web:847606afb34bb57b413b6e',
    messagingSenderId: '428503827243',
    projectId: 'benimflutterprojem-fs',
    authDomain: 'benimflutterprojem-fs.firebaseapp.com',
    storageBucket: 'benimflutterprojem-fs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQwPQiPsM12Xr94fZd6PTD_QjfQAALPI8',
    appId: '1:428503827243:android:780130721491f651413b6e',
    messagingSenderId: '428503827243',
    projectId: 'benimflutterprojem-fs',
    storageBucket: 'benimflutterprojem-fs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2neO1Cx-FhND9KZSl8OAh7m_9f1kkV4s',
    appId: '1:428503827243:ios:2325835118502370413b6e',
    messagingSenderId: '428503827243',
    projectId: 'benimflutterprojem-fs',
    storageBucket: 'benimflutterprojem-fs.appspot.com',
    iosBundleId: 'com.example.flutterprojem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2neO1Cx-FhND9KZSl8OAh7m_9f1kkV4s',
    appId: '1:428503827243:ios:2325835118502370413b6e',
    messagingSenderId: '428503827243',
    projectId: 'benimflutterprojem-fs',
    storageBucket: 'benimflutterprojem-fs.appspot.com',
    iosBundleId: 'com.example.flutterprojem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaLgAi_upwqDHysBRUgGHTNaovJUQIY0M',
    appId: '1:428503827243:web:9e5e2356344ec0d4413b6e',
    messagingSenderId: '428503827243',
    projectId: 'benimflutterprojem-fs',
    authDomain: 'benimflutterprojem-fs.firebaseapp.com',
    storageBucket: 'benimflutterprojem-fs.appspot.com',
  );
}
